[package]
name = "smartcore_vs_linfa"
version = "0.1.0"
edition = "2021"

[dependencies]
smartcore = "0.2.0"
linfa = {version="0.5.0", features=["openblas-static"]}
linfa-linear = "0.5.0"
linfa-logistic = "0.5.0"
linfa-clustering = "0.5.0"
ndarray = "0.15.4"
lazy_static = "1.4.0"
ndarray-rand = "0.14.0"
rand_isaac = "0.3.0"

[dev-dependencies]
criterion = {version="0.3", features=["html_reports"]}

[[bench]]
name = "my_benchmark"
harness = false