name: Benchmarks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt-get install libopenblas-dev gfortran
      - name: run the benchmark
        run: cargo bench --verbose
      - name: move new files to criterion folder
        run: rm -rf criterion; cp -r target/criterion .
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: commit
        run:
          git commit -m "New benchmark results"
          git push
