name: Benchmarks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install libopenblas-dev gfortran zip
      - name: Run tests
        run: cargo bench --verbose
      - name: Zip report
        run: zip -r bench.zip target/criterion
      - name: Archive benchmark results
        uses: actions/upload-artifact@v2
        with:
          name: benchmark-results
          path: bench.zip
